image: gitpod/workspace-full

tasks:
  - name: Build
    init: |
      docker pull postgres:15-alpine
      docker-compose build
    command: |
      printf "Waiting for Voting App at $(gp url 5000) ...\n"
      gp ports await 5000
      cat << EOF
      Voting at $(gp url 5000)
      Results at $(gp url 5001)
      EOF
  - name: Run
    command: docker-compose -f docker-compose.yml up
    openMode: split-right

ports:
  - port: 5000
    onOpen: open-preview
  - port: 5001  # results
    onOpen: ignore
  - port: 5858
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python

github:
  prebuilds:
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
